apiVersion: v1
kind: Service
metadata:
  name: goodwe-mcp
  labels:
    app: goodwe-mcp
spec:
  selector:
    app: goodwe-mcp
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  type: ClusterIP
